// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendApp(arg1) {
  return window['go']['main']['App']['AppendApp'](arg1);
}

export function AppendWebsite(arg1) {
  return window['go']['main']['App']['AppendWebsite'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function MockNotes() {
  return window['go']['main']['App']['MockNotes']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadNote(arg1) {
  return window['go']['main']['App']['ReadNote'](arg1);
}

export function SaveNoteDialog() {
  return window['go']['main']['App']['SaveNoteDialog']();
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteNote(arg1, arg2) {
  return window['go']['main']['App']['WriteNote'](arg1, arg2);
}
