// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {note} from '../models';

export function AppendApp(arg1:models.AppCatalog):Promise<void>;

export function AppendWebsite(arg1:models.WebsiteCatalog):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function Fetch(arg1:string):Promise<string>;

export function GetCatalog():Promise<models.Catalog>;

export function ListNotes():Promise<Array<note.Info>>;

export function MockNotes():Promise<Array<note.Info>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadNote(arg1:string):Promise<string>;

export function SaveNoteDialog():Promise<void>;

export function UnlockVault(arg1:string):Promise<Array<models.PasswordEntry>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteNote(arg1:string,arg2:string):Promise<void>;
