// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {category} from '../models';
import {transaction} from '../models';

export function CreateCategory(arg1:string):Promise<void>;

export function CreateTransaction(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListCategories():Promise<Array<category.Category>>;

export function ListTransaction():Promise<Array<transaction.Transaction>>;
