// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTransaction'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListTransaction() {
  return window['go']['main']['App']['ListTransaction']();
}
