import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppSidebar from '@/components/AppSidebar'

import '@longslark/tailwind/global.css'
import './index.css'

import ToasterProvider from '@/components/ToasterProvider'

import { SidebarProvider, SidebarTrigger } from '@longslark/ui/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <ToasterProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className='w-full'>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ToasterProvider>
      </body>
    </html>
  )
}
